## Challenge One - Working with arrays
E. Thompson


In [3]:
import numpy as np

#### 1. Why doesn't the following code create a 2D array?

In [4]:
# np.array((1, 0, 0), (0, 1, 0), (0, 0, 1, dtype = float)

A. 
- The code has missing bracket after 1, before dtype. 
- array() only takes one list, so needs one list of lists within the parentheses. 
- The lists require square brackets.

In [5]:
answer = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]], dtype = float)
print(answer)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 2. What is the difference between:

In [6]:
a = np.array([0, 0, 0]) # A: This is a 1D array
print(a)

# and 

a = np.array([[0, 0, 0]]) # A: This is a 2D array, with only 1 row
print(a)

[0 0 0]
[[0 0 0]]


#### A 3 by 4 by 4 is created with:

In [7]:
arr = np.linspace(1, 48, 48).reshape(3, 4, 4)
print(arr)

[[[ 1.  2.  3.  4.]
  [ 5.  6.  7.  8.]
  [ 9. 10. 11. 12.]
  [13. 14. 15. 16.]]

 [[17. 18. 19. 20.]
  [21. 22. 23. 24.]
  [25. 26. 27. 28.]
  [29. 30. 31. 32.]]

 [[33. 34. 35. 36.]
  [37. 38. 39. 40.]
  [41. 42. 43. 44.]
  [45. 46. 47. 48.]]]


#### 3. Index or slice to obtain the following: 
###### Hint: use flatten and reshape
3.1 20.0
###### Note: Where I have tried a solution with and without using flatten/reshape, I have given both.

In [8]:
answer = arr.flatten()[19]
print(answer)

# or...

answer = arr[1, 0, 3]
print("\n", answer)

20.0

 20.0


3.2  [9. 10. 11. 12.]

In [9]:
answer = arr[0, 2]
print(answer)

[ 9. 10. 11. 12.]


3.3  [[33. 34. 35. 36.] [37. 38. 39. 40.] [41. 42. 43. 44.] [45. 46. 47. 48.]]

In [10]:
answer = arr[2]
print(answer)

[[33. 34. 35. 36.]
 [37. 38. 39. 40.]
 [41. 42. 43. 44.]
 [45. 46. 47. 48.]]


3.4  [[5. 6.] [21. 22.] [37. 38.]]

In [11]:
answer = arr[:,1,0:2]
print(answer)

# or...

answer = arr.reshape(24, 2)[2::8]
print("\n", answer)

[[ 5.  6.]
 [21. 22.]
 [37. 38.]]

 [[ 5.  6.]
 [21. 22.]
 [37. 38.]]


3.5  [[36. 35.] [40. 39.] [44. 43.] [48. 47.]]

In [12]:
answer = arr.flatten()[::-1].reshape(24, 2)[6::-2]
print(answer)

# or...

answer = arr[2, 0:4, :1:-1]
print("\n", answer)

[[36. 35.]
 [40. 39.]
 [44. 43.]
 [48. 47.]]

 [[36. 35.]
 [40. 39.]
 [44. 43.]
 [48. 47.]]


3.6  [[13. 9. 5. 1] [29. 25. 21. 17.] [45. 41. 37. 33.]]

In [13]:
answer = arr[:, ::-1, 0]
print("\n", answer)


 [[13.  9.  5.  1.]
 [29. 25. 21. 17.]
 [45. 41. 37. 33.]]


3.7  [[1. 4.] [45. 48]]

In [33]:
answer = arr[:,:,::3].reshape(12,2)[::11]
print(answer)

# or...

answer = arr[:,:,[0,3]].reshape(12,2)[[0,11]]
print("\n",answer)

[[ 1.  4.]
 [45. 48.]]

 [[ 1.  4.]
 [45. 48.]]


3.8  [[25. 26. 27. 28] [29. 30. 31. 32] [33. 34. 35. 36.] [37. 38. 39. 40]]

In [15]:
answer = arr.reshape(12, 4)[6:10]
print(answer)

[[25. 26. 27. 28.]
 [29. 30. 31. 32.]
 [33. 34. 35. 36.]
 [37. 38. 39. 40.]]
